language: swift
osx_image: xcode10.2

before_install:
- pod update
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace BayPass.xcworkspace -scheme BayPass -sdk iphonesimulator12.2 -destination "OS=12.2,name=iPhone X" | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'BayPass'

notifications:
     slack: dattworkspace:dOHdcFiG3BrlqZC0zbzXmZiX

# safelist
branches:
  only:
  - master